import { UserProfile } from './services/authService';

export const interlocuteurs: UserProfile[] = [
  {
    uid: 'u1',
    username: '@Stargazer',
    role: "both",
    isPremium: false,
    credits: 10,
    giftableCredits: 2,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 0,
    partnerChangeCount: 0,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'ST123456',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u2',
    username: '@Moonlight',
    role: 'both',
    isPremium: true,
    credits: 50,
    giftableCredits: 10,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 1200,
    partnerChangeCount: 3,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'MN654321',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u3',
    username: '@Aurora',
    role: 'both',
    isPremium: false,
    credits: 25,
    giftableCredits: 5,
    dailyFreeTimeUsed: 600,
    paidTimeAvailable: 300,
    partnerChangeCount: 1,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: false,
    referralCode: 'AU987654',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },{
    uid: 'u1',
    username: '@Stargazer',
    role: 'both',
    isPremium: false,
    credits: 10,
    giftableCredits: 2,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 0,
    partnerChangeCount: 0,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'ST123456',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u2',
    username: '@Moonlight',
    role: 'both',
    isPremium: true,
    credits: 50,
    giftableCredits: 10,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 1200,
    partnerChangeCount: 3,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'MN654321',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u3',
    username: '@wesh',
    role: 'both',
    isPremium: false,
    credits: 25,
    giftableCredits: 5,
    dailyFreeTimeUsed: 600,
    paidTimeAvailable: 300,
    partnerChangeCount: 1,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: false,
    referralCode: 'AU987654',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },{
    uid: 'u1',
    username: '@booo',
    role: 'both',
    isPremium: false,
    credits: 10,
    giftableCredits: 2,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 0,
    partnerChangeCount: 0,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'ST123456',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u2',
    username: '@zeeeer',
    role: 'both',
    isPremium: true,
    credits: 50,
    giftableCredits: 10,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 1200,
    partnerChangeCount: 3,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'MN654321',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u3',
    username: '@ouuuuu',
    role: 'both',
    isPremium: false,
    credits: 25,
    giftableCredits: 5,
    dailyFreeTimeUsed: 600,
    paidTimeAvailable: 300,
    partnerChangeCount: 1,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: false,
    referralCode: 'AU987654',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },{
    uid: 'u1',
    username: '@vvffr',
    role: 'both',
    isPremium: false,
    credits: 10,
    giftableCredits: 2,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 0,
    partnerChangeCount: 0,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'ST123456',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u2',
    username: '@zvrzvrmvm',
    role: 'both',
    isPremium: true,
    credits: 50,
    giftableCredits: 10,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 1200,
    partnerChangeCount: 3,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'MN654321',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u3',
    username: '@vgrzrrz',
    role: 'both',
    isPremium: false,
    credits: 25,
    giftableCredits: 5,
    dailyFreeTimeUsed: 600,
    paidTimeAvailable: 300,
    partnerChangeCount: 1,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: false,
    referralCode: 'AU987654',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },{
    uid: 'u1',
    username: '@zrgrmjnrm',
    role: 'both',
    isPremium: false,
    credits: 10,
    giftableCredits: 2,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 0,
    partnerChangeCount: 0,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'ST123456',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u2',
    username: '@rgvjmrjrj',
    role: 'both',
    isPremium: true,
    credits: 50,
    giftableCredits: 10,
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 1200,
    partnerChangeCount: 3,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: true,
    referralCode: 'MN654321',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  {
    uid: 'u3',
    username: '@rzbzrmbjmrb',
    role: 'both',
    isPremium: false,
    credits: 25,
    giftableCredits: 5,
    dailyFreeTimeUsed: 600,
    paidTimeAvailable: 300,
    partnerChangeCount: 1,
    dailyResetDate: new Date().toDateString(),
    hasCompletedSetup: false,
    referralCode: 'AU987654',
    createdAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
  },
  
];

export const generateRandomUserProfile = (): UserProfile => {
  const usernames = ['@Eclipse', '@Moonlight', '@Stargazer', '@Phoenix', '@Mystic', '@Aurora', '@Cosmic', '@Zen'];
  const roles: UserProfile['role'][] = ['talk', 'listen', 'both'];
  const randomIndex = Math.floor(Math.random() * usernames.length);
  const now = new Date();

  return {
    uid: `uid-${Math.random().toString(36).slice(2, 8)}`,
    username: usernames[randomIndex],
    role: roles[Math.floor(Math.random() * roles.length)],
    isPremium: Math.random() < 0.5,
    credits: Math.floor(Math.random() * 100),
    giftableCredits: Math.floor(Math.random() * 10),
    dailyFreeTimeUsed: 0,
    paidTimeAvailable: 0,
    partnerChangeCount: 0,
    dailyResetDate: now.toDateString(),
    hasCompletedSetup: Math.random() < 0.8,
    referralCode: `RF${Math.floor(Math.random() * 1000000)}`,
    createdAt: now.toISOString(),
    lastActiveAt: now.toISOString(),
  };
};